---
# - name: start cloud_sql_proxy
#     -service:
#       name: cloud-sql-proxy
#       state: started
#       enabled: yes


- name: start cloud_sql_proxy
  ansible.builtin.systemd:
    state: started
    daemon_reload: yes
    name: cloud-sql-proxy
    enabled: yes
