---
- name: download CloudSQL Auth Proxy
  ansible.builtin.get_url:
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    dest: /usr/local/bin/cloud_sql_proxy
    mode: '550'

- name: add cloud-sql-proxy.conf file
  template:
    src: cloud-sql-proxy.j2
    dest: /etc/systemd/system/cloud-sql-proxy.service
  notify: start cloud_sql_proxy
