---
- name: Add the user for cloudsql
  ansible.builtin.user:
    name: {{ cloudsql_srvc_user_name }}
    shell: /usr/bin/false
    system: yes

- name: download CloudSQL Auth Proxy
  ansible.builtin.get_url:
    url: https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
    dest: "{{ cloud_sql_proxy_file_path }}"/cloud_sql_proxy
    mode: '550'
    owner: {{ cloudsql_srvc_user_name }}

- name: add cloud-sql-proxy.conf file
  template:
    src: cloud-sql-proxy.j2
    dest: /etc/systemd/system/cloud-sql-proxy.service
  notify: start cloud_sql_proxy






# wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
#
# chmod +x cloud_sql_proxy
#
# curl https://gist.githubusercontent.com/ErikSaunier/e8ff253acc8d18a57192d53b6850300f/raw/16bdaf10a579995acc784e46c7b78f7cf44115c3/cloud-sql-proxy.service /etc/systemd/system/cloud-sql-proxy.service
#
# change <INSTANCE_CONNECTION_NAME>
#
# sudo systemctl daemon-reload
#
# sudo systemctl enable cloud-sql-proxy
#
#
# sudo systemctl start cloud-sql-proxy
#
# apt-get install default-mysql-client
# mysql -u USERNAME -p --host 127.0.0.1
