---
- name: Add the user for petclinic
  ansible.builtin.user:
    name: petclinic
    shell: /usr/bin/false
    system: yes


- name: Create a directory petclinic
  ansible.builtin.file:
    path: /opt/petclinic
    state: directory
    owner: petclinic
    group: petclinic
    recurse: yes

- name: Install boto3 and botocore with pip3 module
  pip:
    name:
    - boto3
    - botocore
    executable: pip-3.7

- name: Download jar
  gc_storage:
    bucket: gcp-2021-2-artifacts-dykaliuk
    object: spring-petclinic-2.5.0-SNAPSHOT.jar
    dest: /opt/petclinic/petclinic.jar
    mode: get
    gs_access_key: GOOGI2ZKG6IH4GRO6MQ3ZKCQ
    gs_secret_key: ShgKTfDS4khpXtwSHXM/CUffeFl6OiBcAc4ILYu1

- name: template petclinic service file
  ansible.builtin.template:
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
  notify: Daemon_reload

- name: started petclinic as service
  ansible.builtin.service:
    name: petclinic
    state: restarted
    enabled: yes
