---
- name: Add the user for petclinic
  ansible.builtin.user:
    name: "{{ petclinic_srvc_user_name }}"
    shell: /usr/bin/false
    system: yes

- name: Create a directory petclinic
  ansible.builtin.file:
    path: "{{ petclinic_dir }}"
    state: directory
    owner: "{{ petclinic_srvc_user_name }}"
    group: "{{ petclinic_srvc_user_name }}"
    recurse: yes

- name: copy petclinic jar from bucket
  ansible.builtin.shell: "gsutil cp gs://{{ petclinic_source_bucket }}/{{ petclinic_source_file }} {{ petclinic_dir }}/{{ petclinic_local_file_name }}"

- name: template petclinic service file
  ansible.builtin.template:
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
  notify: start petclinic service

# - name: start petclinic as a service
#   ansible.builtin.service:
#     name: petclinic
#     state: restarted
#     enabled: yes
