---
- name: Add the user for petclinic
  ansible.builtin.user:
    name: petclinic
    shell: /usr/bin/false
    system: yes


- name: Create a directory petclinic
  ansible.builtin.file:
    path: /opt/petclinic
    state: directory
    owner: petclinic
    group: petclinic
    recurse: yes

- name: Download jar
  gc_storage:
    bucket: gcp-2021-2-artifacts-dykaliuk
    object: spring-petclinic-2.5.0-SNAPSHOT.jar
    dest: /opt/petclinic/petclinic.jar
    mode: get

- name: template petclinic service file
  ansible.builtin.template:
    src: petclinic.service.j2
    dest: /etc/systemd/system/petclinic.service
  notify: Daemon_reload

- name: started petclinic as service
  ansible.builtin.service:
    name: petclinic
    state: restarted
    enabled: yes
